mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'waymilky-vim_puppet'
mod 'jriviere-windows_ad', '0.3.2'