mod 'dsc-auditpolicydsc'
mod 'dsc-computermanagementdsc'
mod 'dsc-powershellget'
mod 'dsc-sharepointdsc'
mod 'dsc-sqlserverdsc'
mod 'dsc-windowsdefender'
mod 'dsc-xwebadministration'
mod 'ianoberst-xml_fragment'
mod 'pltraining/dockeragent'
mod 'puppet-xmlfile'
mod 'puppet/nginx'
mod 'puppetlabs-augeas_core'
mod 'puppetlabs-chocolatey'
mod 'puppetlabs-dsc_lite', '3.2.0'
mod 'puppetlabs-dsc'
mod 'puppetlabs-iis'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/docker'
mod 'puppetlabs/pwshlib'
mod 'puppetlabs/stdlib'